### ISSUE TITLE
Only certain ligatures work in vim

### ISSUE THREAD

**Issue by codecalec** [cog1to/st-ligatures#1]
Thanks so much for this patch.

All ligatures work fine in nano but not vim where only certain patterns work.
Do you need to edit your vimrc?

![screenshot-1586045061](https://user-images.githubusercontent.com/16204819/78463810-a8353580-76e1-11ea-97df-1525281ed825.png)

**Comment by cog1to** [comment]
They all work, but there are some limitations. Because of the current drawing engine, I haven't found a way to span ligatures across different colors, so when color change occurs in the middle of a ligature sequence, they break into individual symbols.

This happens when vim cannot recognize the syntax and tries to do its best to guess. In actual code  with proper syntax support, or with `syntax off`, it will display all ligatures correctly.

I updated the test file to get rid of some artifacts, and also added examples for different languages, so you can test those if you have appropriate language plugins for vim.
